default: &default
  address:              127.0.0.1
  port:                 1025

development:
  address: "smtp.mailgun.org"
  port: '587'
  enable_starttls_auto: true
  user_name: "postmaster@sandboxaad8223281b447c1b3b234da95b4fff9.mailgun.org"
  password: "jekan777"
  authentication: 'plain'
  domain: 'shoes-style69.ru'

production:
  address: "smtp.mailgun.org"
  port: '587'
  enable_starttls_auto: true
  user_name: "postmaster@sandboxaad8223281b447c1b3b234da95b4fff9.mailgun.org"
  password: "jekan777"
  authentication: 'plain'
  domain: 'shoes-style69.ru'
